"""Provider response parsing helpers."""

from __future__ import annotations

import re

from engineering.models.core import PatchResponse


def parse_patch_response(text: str, *, provider_name: str) -> PatchResponse:
    diff_match = re.search(r"```diff\s*(.*?)```", text, re.DOTALL)
    if diff_match:
        diff = diff_match.group(1).strip() + "\n"
    elif re.search(r"^(diff --git|--- |\+\+\+ |@@ )", text, re.MULTILINE):
        diff = text.strip() + "\n"
    else:
        diff = ""
    files = tuple(dict.fromkeys(re.findall(r"^\+\+\+ b/(.+)$", diff, re.MULTILINE)))
    confidence_match = re.search(r"Confidence:\s*([0-9.]+)", text, re.IGNORECASE)
    confidence = float(confidence_match.group(1)) if confidence_match else 0.5
    summary_match = re.search(r"Engineering Summary:\s*(.*?)(?:\n\n|$)", text, re.DOTALL | re.IGNORECASE)
    reasoning_match = re.search(r"Reasoning Summary:\s*(.*?)(?:\n\n|$)", text, re.DOTALL | re.IGNORECASE)
    return PatchResponse(
        unified_diff=diff,
        engineering_summary=(summary_match.group(1).strip() if summary_match else "Patch generated by provider."),
        confidence=max(0.0, min(confidence, 1.0)),
        modified_files=files,
        reasoning_summary=(reasoning_match.group(1).strip() if reasoning_match else ""),
        provider_name=provider_name,
        raw_text=text,
    )
