"""Engineering report generation."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from confidence.models import ConfidenceAssessment
from reports.models import EngineeringReport


@dataclass(slots=True)
class EngineeringReportGenerator:
    """Builds a typed report from execution evidence."""

    def generate(self, *, evidence: dict[str, Any], confidence: ConfidenceAssessment) -> EngineeringReport:
        return EngineeringReport(
            execution_id=str(evidence.get("execution_id", "unknown")),
            issue_summary=str(evidence.get("issue_summary", "")),
            repository=str(evidence.get("repository_name", "unknown")),
            root_cause=str(evidence.get("root_cause", "not available from execution artifacts")),
            files_read=tuple(evidence.get("files_read", ())),
            files_modified=tuple(evidence.get("files_modified", ())),
            prompt_summary=str(evidence.get("prompt_summary", "workflow prompt generated by engineering pipeline")),
            patch_summary=str(evidence.get("patch_summary", "see workflow artifacts")),
            validation=str(evidence.get("validation", evidence.get("status", "unknown"))),
            tests=tuple(evidence.get("tests_executed", ())),
            retries=int(evidence.get("retry_count", 0)),
            confidence=confidence,
            timeline=tuple(evidence.get("timeline", ())),
            final_decision=confidence.decision_recommendation,
            next_recommendation=str(evidence.get("next_recommendation", confidence.decision_recommendation)),
        )
